apiVersion: v1
kind: Service
metadata:
  name: webserver-loadbalancer
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80