apiVersion: v1
kind: Service
metadata:
  name: webserver-nodeport
  namespace: web
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - port: 80 # pod ip
      targetPort: 80 # service ip
      nodePort: 30007 # node ip it exposes outside the cluster