apiVersion: v1
kind: Deployment
metadata: 
  name: my-deployment
  namespace: default
  labels:
    app: 5g
    tier: development
    environment: development
    version: v1.2
    managedby: person1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template: 
    metadata: 
      labels:
        app: my-app
    spec:
      containers:
        name: nginx
        image: nginx:latest
        port: 8080
      env:
      resources:
      volumes:
      livenessProbe:
      readinessProbe:
