apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset         
  labels:
    app: 5g
    tier: backend
spec:
  replicas: 3                    
  selector:                       
    matchLabels:
      app: 5g
      tier: backend
    matchExpressions:
      - key: environment
        operator: In
        values:
          - dev
          - prod
  template:                       
    metadata:
      labels:                     
        app: 5g
        tier: backend
        environment: dev
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
